sudo: false
language: go
go:
  - 1.x
  - tip
matrix:
  allow_failures:
    - go: tip
  fast_finish: true
script:
  - go get -t -v ./...
  - diff -u <(echo -n) <(gofmt -d -s .)
  - go tool vet .
  - go test -v -race ./...
