sudo: false
language: go
go:
    - 1.x
    - 1.7.x
    - 1.6.x
    - 1.5.x
    - 1.4.x
    - tip
before_install:
    - go get github.com/mattn/goveralls
    - go get golang.org/x/tools/cmd/cover
    - go get github.com/mattn/goveralls
    - go get github.com/modocache/gover

before_script:
    - go fmt ./...
    - go vet ./...
script:
    - go test -coverprofile=strutils.coverprofile
    - gover
    - goveralls -coverprofile=gover.coverprofile -service=travis-ci
matrix:
    allow_failures:
        - go: tip
          fast_finish: true
