name: go-strutil
on:
  schedule:
    - cron:  '*/15 * * * *'    # At every 15th minute
  push:
  pull_request:

jobs:
  build:
    strategy:
      matrix:
       symbol-list: [1.19.0, 1.18.0, 1.17.0, 1.16.0, 1.15.0, 1.14.0]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    # Setup Go
    - name: $
      uses: actions/setup-go@v2
      with:
        go-version: '>=$'
        check-latest: true
    
    # Install all the dependencies
    - name: Install dependencies
      run: |
        go version
        go get github.com/mattn/goveralls
        go get golang.org/x/tools/cmd/cover
        go get github.com/mattn/goveralls
        go get github.com/modocache/gover
        go get github.com/dustin/go-humanize
        go get get github.com/k0kubun/pp
        go get github.com/awalterschulze/gographviz
        
    # Run build of the application
    - name: Run build
      run: go build . 
      
    # Run vet & lint on the code
    - name: Run vet & lint
      run: |
        go vet .
        golint .
    
    # Run testing on the code
    - name: Run testing
      run: |
        go test -v -test.parallel 4 -race -run Test_strutils_Assert*
