name: go-strutil
on:
  schedule:
    - cron:  '*/15 * * * *'    # At every 15th minute
  push:
  pull_request:

jobs:
  build:
    strategy:
      matrix:
       go: ['1.19', '1.18', '1.17', '1.16', '1.15', '1.14']
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    # Setup Go
    - name: Go v${{ matrix.go }} 
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }} 
        check-latest: true
        cache: true
    
    # Install all the dependencies
    - name: Install dependencies
      run: |
        go version
        go get get github.com/Masterminds/glide
        go get github.com/mattn/goveralls
        go get golang.org/x/tools/cmd/cover
        go get github.com/mattn/goveralls
        go get github.com/modocache/gover
        go get github.com/dustin/go-humanize
        go get github.com/k0kubun/pp
        go get github.com/awalterschulze/gographviz
        
    # Run build of the application
    - name: Run build
      run: go build . 
      
    # Run vet & lint on the code
    - name: Run vet
      run: |
        go vet .
    
    # Run testing on the code
    - name: Run testing
      run: |
        go test -v -test.parallel 4 -race -run Test_strutils_Assert*
